name: Configure test
on:
  push:
  workflow_dispatch:
jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install libglib2.0-dev 
      - run: ./configure
