name: Configure test
on:
  push:
  workflow_dispatch:
jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update
      - run: sudo apt-get install libglib2.0-dev libaio-dev
      - run: sudo apt-get install libcurl4-openssl-dev
      - run: ./configure --prefix=$(pwd)/OUT && make install
      - uses: actions/upload-artifact@v4
        with:
          name: qemu
          path: OUT/
